language: objective-c
osx_image: xcode9.3

install:
    - bundle install
    - pod repo update > /dev/null
    - ./install.sh

env:
    - PLATFORM=ios
    - PLATFORM=mac

script:
    - bundle exec fastlane $PLATFORM test
