language: objective-c
osx_image: xcode10.3

install:
    # Bundler 2+ is required
    - gem install bundler
    - bundle install
    - pod repo update > /dev/null
    - ./install.sh

env:
    - PLATFORM=ios
    - PLATFORM=mac

script:
    - bundle exec fastlane $PLATFORM test
